from __future__ import annotations

from core import modloaders as core_modloaders
from core.constants import (
    MAX_VERSION_ID_LENGTH,
    MAX_CATEGORY_LENGTH,
    MAX_USERNAME_LENGTH,
    MAX_LOADER_VERSION_LENGTH,
    MAX_VERSIONS_IMPORT_PAYLOAD,
    MAX_MODS_IMPORT_PAYLOAD,
    MAX_MODPACKS_IMPORT_PAYLOAD,
    MAX_WORLDS_IMPORT_PAYLOAD,
    MAX_MOD_SLUG_LENGTH,
    MAX_MODPACK_SLUG_LENGTH,
    MAX_VERSION_LABEL_LENGTH,
    MAX_FILENAME_LENGTH,
    MAX_ARCHIVE_SUBFOLDER_LENGTH,
    MAX_VERSION_DISPLAY_NAME_LENGTH,
    MAX_VERSION_IMAGE_URL_LENGTH,
    MAX_VERSION_IMAGE_UPLOAD_BYTES,
    MAX_STORAGE_OVERRIDE_PATH_LENGTH,
)


__all__ = [
    "GITHUB_RAW_VERSION_URL",
    "REMOTE_TIMEOUT",
    "MAX_VERSION_ID_LENGTH",
    "MAX_CATEGORY_LENGTH",
    "MAX_USERNAME_LENGTH",
    "MAX_LOADER_VERSION_LENGTH",
    "MAX_VERSIONS_IMPORT_PAYLOAD",
    "MAX_MODS_IMPORT_PAYLOAD",
    "MAX_MODPACKS_IMPORT_PAYLOAD",
    "MAX_WORLDS_IMPORT_PAYLOAD",
    "MAX_PAYLOAD_SIZE",
    "MAX_MOD_SLUG_LENGTH",
    "MAX_MODPACK_SLUG_LENGTH",
    "MAX_VERSION_LABEL_LENGTH",
    "MAX_FILENAME_LENGTH",
    "MAX_ARCHIVE_SUBFOLDER_LENGTH",
    "MAX_VERSION_DISPLAY_NAME_LENGTH",
    "MAX_VERSION_IMAGE_URL_LENGTH",
    "MAX_VERSION_IMAGE_UPLOAD_BYTES",
    "MAX_STORAGE_OVERRIDE_PATH_LENGTH",
    "CURRENT_MD_VERSION",
    "HISTOLAUNCHER_WEB_ORIGINS",
    "HISTOLAUNCHER_WEBSITE_ORIGIN",
    "HISTOLAUNCHER_ACCOUNTS_ORIGIN",
    "HISTOLAUNCHER_TEXTURES_ORIGIN",
    "HISTOLAUNCHER_WEB_PROXY_PREFIX",
    "HISTOLAUNCHER_ACCOUNTS_PROXY_PREFIX",
    "HISTOLAUNCHER_TEXTURES_PROXY_PREFIX",
    "FORGE_INSTALL_BLOCKED_VERSIONS",
    "VALID_LOADER_TYPES",
    "VALID_MOD_LOADERS",
    "VALID_ADDON_TYPES",
    "VALID_VERSION_STORAGE_OVERRIDE_MODES",
    "CANCELLED_OPERATION_ERROR_MESSAGE",
]


GITHUB_RAW_VERSION_URL = (
    "https://raw.githubusercontent.com/KerbalOfficial/Histolauncher/main/version.dat"
)
REMOTE_TIMEOUT = 5.0

MAX_PAYLOAD_SIZE = MAX_VERSIONS_IMPORT_PAYLOAD

CURRENT_MD_VERSION = "1.0"

HISTOLAUNCHER_WEB_ORIGINS = (
    "https://histolauncher.org",
    "https://histolauncher.pages.dev",
)

HISTOLAUNCHER_WEBSITE_ORIGIN = HISTOLAUNCHER_WEB_ORIGINS[0]
HISTOLAUNCHER_ACCOUNTS_ORIGIN = "https://accounts.histolauncher.org"
HISTOLAUNCHER_TEXTURES_ORIGIN = "https://textures.histolauncher.org"

HISTOLAUNCHER_WEB_PROXY_PREFIX = "/histolauncher-proxy/web"
HISTOLAUNCHER_ACCOUNTS_PROXY_PREFIX = "/histolauncher-proxy/accounts"
HISTOLAUNCHER_TEXTURES_PROXY_PREFIX = "/histolauncher-proxy/textures"

FORGE_INSTALL_BLOCKED_VERSIONS: set[str] = set()

VALID_LOADER_TYPES = tuple(core_modloaders.SUPPORTED_LOADER_TYPES)
VALID_MOD_LOADERS = tuple(core_modloaders.SUPPORTED_LOADER_TYPES)
VALID_MODPACK_LOADERS = (*VALID_MOD_LOADERS, "vanilla")
VALID_ADDON_TYPES = ("mods", "resourcepacks", "shaderpacks", "modpacks", "datapacks")
VALID_VERSION_STORAGE_OVERRIDE_MODES = {"default", "global", "version", "custom"}

CANCELLED_OPERATION_ERROR_MESSAGE = "Operation cancelled by user"
